# 应用名称
# type: string(dns1123)
# default value: null
# required
# nhctl param: [NAME]
# uniq
name: nocalhost

# 应用 manifest 文件用何种类型方式组织
# type: select，options：helm/rawManifest/kustomize
# default value: null
# required
# nhctl param: --type,-t
manifestType: helm

# 应用 manifest，chart 等文件相对于根目录的存放位置, manifest 类型可以指定多个目录
# type: string[]
# default value: ["."]
# required
resourcePath: ["deployments/chart"]

# 应用安装的时候是否尝试以最小资源安装（预留，以后支持）
# type: boolean
# default value: false
# optional
# nhctl param: TODO
minimalInstall: false

# 应用安装前，前置执行的job
# type: object[]
# default value: []
# optional
onPreInstall:

  # Job yaml 相对于源码目录的位置
  # type: string
  # default value: null
  # required
  - path: "job-1.yaml"
    
    # Job yaml 相对于源码目录的位置（预留，以后支持）
    # type: string
    # default value: null
    # required
    name: xxx-job

    # job 执行的先后顺序，小的先执行
    # type: integer
    # default value: 0
    # optional
    priority: -1
  - path: "job-2.yaml"
    priority: 5

# 应用安装后执行的job（预留，以后支持）
# type: object[]
# default value: []
# optional
onPostInstall:
  - path: "job-1.yaml"
    priority: 10
  - path: "job-2.yaml"
    priority: 5

# 应用卸载前，前置执行的job（预留，以后支持）
# type: object[]
# default value: []
# optional
onPreUninstall:
  - path: "job-1.yaml"
    priority: 10
  - path: "job-2.yaml"
    priority: 5

# 应用卸载后执行的job（预留，以后支持）
# type: object[]
# default value: []
# optional
onPostUninstall:
  - path: "job-1.yaml"
    priority: 10
  - path: "job-2.yaml"
    priority: 5

# 应用内的服务列表
# type: object[]
# default value: []
# optional
services:

    # 服务名称，与服务名称的正则表达式两者只能配置一个，如果同时配置，则 name 属性生效，nameRegex 属性不生效
    # type: string
    # default value: null
    # optional
  - name: service1
    # 服务名称的正则表达式（预留）
    # type: string
    # default value: null
    # optional
    nameRegex: .*-mariadb
    # 服务对应的 Kubernetes 的工作负载类型
    # type: select, options: deployment/statefulset/pod/job/cronjob/daemonset 大小写不敏感
    # default value: deployment
    # required
    serviceType: deployment
    # 服务对应的源代码的 Git Clone 地址
    # type: string
    # default value: null
    # required
    gitUrl: "https://github.com/nocalhost/nocalhost.git"

    # 开发此服务的开发环境的镜像
    # type: string
    # default value: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/golang:latest
    # required
    devContainerImage: "codingcorp-docker.pkg.coding.net/nocalhost/dev-images/golang:latest"

    # 开发服务进入开发环境的 shell 类型（预留，以后支持）
    # type: string
    # default value: "/bin/sh"
    # optional
    devContainerShell: "bash"
    
    # 开发模式中文件同步类型（预留，以后支持）
    # "send" 为单向同步到容器内，"sendreceive" 为双向同步
    # type: select，send/sendreceive
    # default value: "send"
    # optional
    syncType: send

    # 开发模式中同步的文件目录列表，指代码目录的相对路径
    # type: string[]
    # default value: ["."]
    # optional
    syncDirs: 
      - "./src"
      - "./pkg/fff"

    # 开发模式中忽略的文件目录列表（预留，以后支持）
    # type: string[]
    # default value: []
    # optional
    ignoreDirs:
      - ".git"
      - "./build"
    
    # 开发模式需要转发端口到本地，支持本地固定和随机端口两种方法
    # localPort:remotePort
    # type: string[]
    # default value: []
    # optional
    devPort:
      - 8080:8080
      - :8000  # random localPort, remotePort 8000

    # 服务启动所依赖的 pod 标签选择器(此服务会等待标签选择器选中的 pod 启动完毕才启动)
    # type: string[]
    # default value: []
    # optional
    dependPodsLabelSelector:
      # 只要包含其中一个选择器就会被选中
      # 多个 labels 选择器是 and 的关系，只有全部被依赖的服务启动完成，服务的业务容器才会启动
      - "name=mariadb"
      - "app.kubernetes.io/name=mariadb"

    # 服务启动所依赖的 pod 标签选择器(此服务会等待标签选择器选中的 job 执行完毕才启动)
    # type: string[]
    # default value: []
    # optional
    dependJobsLabelSelector:
      - "name=init-job"
      - "app.kubernetes.io/name=init-job"

    # 开发容器的工作目录（本地源码会同步到此容器的工作目录，后续支持：此工作目录会使用 PV 持久化，方便后续持续开发）
    # type: string
    # default value: "/home/nocalhost-dev"
    # optional
    workDir: "/home/nocalhost-dev"

    # 开发容器的持久化存储目录（这个目录下的内容会被以 PV 形式保存，方便后续开发复用）（预留，以后支持）
    # type: string[]
    # default value: ["/home/nocalhost-dev"]
    # optional
    persistentVolumeDir: 
      - "/home/nocalhost-dev"

    # 服务的构建命令（用于在代码变动后执行编译）（预留，以后支持）
    # type: string
    # default value: ""
    # optional
    buildCommand: "./gradlew package"

    # 服务启动命令（预留，以后支持）
    # type: string
    # default value: ""
    # optional
    runCommand: "./gradlew bootRun"

    # 服务调试启动命令（预留，以后支持）
    # type: string
    # default value: ""
    # optional
    debugCommand: "./gradlew bootRun --debug-jvm"

    # 热加载服务启动命令（预留，以后支持）
    # type: string
    # default value: ""
    # optional
    hotReloadRunCommand: "kill `ps -ef|grep -i gradlew| grep -v grep| awk '{print $2}'`; gradlew bootRun"

    # 热加载服务调试启动命令（预留，以后支持）
    # type: string
    # default value: ""
    # optional
    hotReloadDebugCommand: "kill `ps -ef|grep -i gradlew| grep -v grep| awk '{print $2}'`; gradlew bootRun --debug-jvm"

    # 服务调试端口（预留，以后支持）
    # type: string
    # default value: ""
    # optional
    remoteDebugPort: 5005

    # 使用 VSCode 的 dev-container 机制作为开发基础环境（预留，未来实现）
    # type: string
    # default value: ""
    # optional
    useDevContainer: false

  - name: service2
    nameRegex: