- name: productpage
  serviceType: deployment
  dependLabelSelector:
    pods:
      - "productpage"
      - "details"
  containers:
    - name: productpage
      install:
        env:
          - name: ENV_INJECT_EXAM
            value: ANNOTATIONS