- name: productpage
  serviceType: deployment
  containers:
    - name: productpage
      install:
        env:
          - name: ENV_INJECT_EXAM
            value: BASE

- name: details
  serviceType: deployment
  containers:
    - install:
        env:
          - name: ENV_INJECT_EXAM
            value: BASE

- name: ratings
  serviceType: deployment
  dependLabelSelector:
    pods:
      - "productpage"
  containers:
    - install:
        env:
          - name: ENV_INJECT_EXAM
            value: BASE

- name: reviews
  serviceType: deployment
  dependLabelSelector:
    pods:
      - "productpage"
  containers:
    - install:
        env:
          - name: ENV_INJECT_EXAM
            value: BASE

- name: authors
  serviceType: deployment
  dependLabelSelector:
    pods:
      - "productpage"
  containers:
    - install:
        env:
          - name: ENV_INJECT_EXAM
            value: BASE
