apiVersion: batch/v1
kind: Job
metadata:
  name: print-num-01
spec:
  template:
    spec:
      containers:
      - name: print-num
        image: codingcorp-docker.pkg.coding.net/nocalhost/public/sleep-and-print-num:0.1
        command: ["go", "run", "print-num.go", "10"]
      restartPolicy: Never
  backoffLimit: 4
