preInstalls:
  - path: pre-install/print-num-job-01.yaml
  - path: pre-install/print-num-job-02.yaml
    weight: "10"  # 权重，越小优先安装
  - path: pre-install/print-num-job-03.yaml
    weight: "-5"

appConfig:
  name: bookinfo
  type: manifest
  resourcePath: manifest/templates

svcConfigs:
  - name: details
    type: deployment
    gitUrl: https://github.com/nocalhost/bookinfo-details.git
    devLang: ruby  # java|go|node|php
    devImage: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/ruby:latest  # 可选参数：自定义开发容器
    # sideCarImage: codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-sidecar:v1
    workDir: /home/nocalhost-dev   # sidecar 和业务容器的公共目录，kubectl exec 进去就是家目录 k8s containers.workingDir
    localWorkDir: /home/coding   # 插件自动拉代码并保存的本地工作空间
    sync:  # 用户配置的同步目录
    - ./   # 本地工作目录同步到远程 workDir 目录（脚本语言推荐），注意需要使用 empty dir 挂载到业务容器和工作容器对应的目录下，实现容器间共享存储。
    ignore:
      - tests # 忽略本地 /test 目录不同步
      - .github
    sshPort:
      localPort: 12347
      sshPort: 22
    command: ["kill `ps -ef|grep -i gradlew| grep -v grep| awk '{print $2}'`", "gradlew", "bootrun"]
  - name: ratings
    type: deployment
    gitUrl: https://github.com/nocalhost/bookinfo-ratings.git
    devLang: node
    devImage: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/node:latest
    # sideCarImage: codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-sidecar:latest
    workDir: /home/nocalhost-dev
    localWorkDir: /home/coding
    sync:
    - ./
    jobs:
    - "dep-job"
    pods:
    - "productpage"
    - "app.kubernetes.io/name=productpage"
  - name: productpage
    type: deployment
    gitUrl: https://github.com/nocalhost/bookinfo-productpage
    devLang: python
    devImage: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/python:latest
    # sideCarImage: codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-sidecar:latest
    workDir: /home/nocalhost-dev
    localWorkDir: /home/coding
    sync:
    - ./
    devPort:
    - :9080  # 打通应用的调试端口，使用 port-forward 一致的格式 [locaPort:remotePort]
    jobs:
    - "dep-job"
  - name: reviews
    type: deployment
    gitUrl: https://github.com/nocalhost/bookinfo-reviews.git
    devLang: java
    devImage: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/java:latest
    # sideCarImage: codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-sidecar:latest
    workDir: /home/nocalhost-dev
    localWorkDir: /home/coding
    sync:
    - ./
    pods:
    - "productpage"
