configProperties:
  version: v2
  envFile: env.dev

application:
  name: bookinfo
  manifestType: rawManifest
  resourcePath: ["manifest/templates"]
  ignoredPath: []
  onPreInstall: 
    - path: manifest/templates/pre-install/print-num-job-01.yaml
      weight: "1"
    - path: manifest/templates/pre-install/print-num-job-02.yaml
      weight: "-5"
  env: 
    - name: DEBUG
      value: ${DEBUG:-false}
    - name: DOMAIN
      value: ${DOMAIN:-www.coding.com}
  services:
    - name: productpage
      serviceType: deployment
        jobs:
          - "dep-job"
      containers:
        - name: productpage
          install: 
            env: 
              - name: DEBUG
                value: "false"
              - name: DOMAIN
                value: "codingcorp.coding.com"
            portForward:   
              - 39080:9080
          dev:
            gitUrl: https://e.coding.net/codingcorp/nocalhost/bookinfo-productpage.git
            image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/python:3.7.7-slim-productpage
            shell: bash
            workDir: /home/nocalhost-dev
            resources:
              limits:
                cpu: "1"
                memory: 1Gi
              requests:
                cpu: "0.5"
                memory: 512Mi
            persistentVolumeDirs: 
              - path: "/home"
                capacity: 10Gi
            sync: 
              type: send
              filePattern: 
                - ./
              ignoreFilePattern:
                - ".git"
            env: 
            - name: DEBUG
              value: "true"
            portForward:
            - 39080:9080
    - name: details
      serviceType: deployment
      containers:
        - install: 
            env: 
              - name: DEBUG
                value: "false"
          dev:
            gitUrl: https://e.coding.net/codingcorp/nocalhost/bookinfo-details.git
            image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/ruby:2.7.1-slim
            shell: bash
            workDir: /home/nocalhost-dev
            sync: 
              type: send
              filePattern: 
                - ./
              ignoreFilePattern:
                - ".git"
            env: 
            - name: DEBUG
              value: "true"
    - name: ratings
      serviceType: deployment
      dependLabelSelector: 
        pods: 
          - "productpage"
          - "app.kubernetes.io/name=productpage"
        jobs:
          - "dep-job"
      containers:
        - install: 
            env: 
              - name: DEBUG
                value: "false"
          dev:
            gitUrl: https://e.coding.net/codingcorp/nocalhost/bookinfo-ratings.git
            image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/node:12.18.1-slim
            shell: bash
            workDir: /home/nocalhost-dev
            sync: 
              type: send
              filePattern: 
                - ./
              ignoreFilePattern:
                - ".git"
            env: 
            - name: DEBUG
              value: "true"
    - name: reviews
      serviceType: deployment
      dependLabelSelector: 
        pods: 
          - "productpage"
      containers:
        - install: 
            env: 
              - name: DEBUG
                value: "false"
          dev:
            gitUrl: https://e.coding.net/codingcorp/nocalhost/bookinfo-reviews.git
            image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/java:latest
            shell: bash
            workDir: /home/nocalhost-dev
            sync: 
              type: send
              filePattern: 
                - ./
              ignoreFilePattern:
                - ".git"
            env: 
            - name: DEBUG
              value: "true"
