name: bookinfo
manifestType: rawManifest
resourcePath: ["manifest/templates"]

onPreInstall:
  - path: manifest/templates/pre-install/print-num-job-01.yaml
    weight: "1"
  - path: manifest/templates/pre-install/print-num-job-02.yaml
    weight: "-5"

services:
  - name: productpage
    serviceType: deployment
    gitUrl: https://github.com/nocalhost/bookinfo-productpage
    devContainerImage: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/python:3.7.7-slim-productpage
    workDir: /root/nocalhost-dev
    persistentVolumeDirs: 
    - path: /root
    devContainerShell: ""
    devPorts:
    - 39080:9080
    dependJobsLabelSelector:
    - "job-name=dep-job"
    syncFilePattern:
    - .
    ignoreFilePattern:
    - .git

  - name: details
    serviceType: deployment
    gitUrl: https://github.com/nocalhost/bookinfo-details.git
    devContainerImage: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/ruby:2.7.1-slim
    syncFilePattern:
    - .
    ignoreFilePattern:
    - .git
    workDir: /home/nocalhost-dev
    
  - name: ratings
    serviceType: deployment
    gitUrl: https://github.com/nocalhost/bookinfo-ratings.git
    devContainerImage: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/node:12.18.1-slim
    workDir: /home/nocalhost-dev
    syncFilePattern:
    - .
    ignoreFilePattern:
    - .git
    dependJobsLabelSelector:
    - "job-name=dep-job"
    dependPodsLabelSelector:
    - "productpage"
    - "app.kubernetes.io/name=productpage"
    
  - name: reviews
    serviceType: deployment
    gitUrl: https://github.com/nocalhost/bookinfo-reviews.git
    devContainerImage: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/java:latest
    workDir: /home/nocalhost-dev
    syncFilePattern:
    - .
    ignoreFilePattern:
    - .git
    dependPodsLabelSelector:
    - "productpage"
