configProperties:
  version: v2
  envFile: env.dev

application:
  name: bookinfo
  manifestType: kustomizeLocal
  resourcePath: ["kustomize/base"]
  env: 
    - name: DEBUG
      value: ${DEBUG:-false}
    - name: DOMAIN
      value: ${DOMAIN:-coding.net}
  services:
    ${_INCLUDE_:-./base-services.yaml | nindent 4}