configProperties:
  version: v2
  envFile: env.dev

application:
  name: bookinfo
  manifestType: rawManifest
  resourcePath: ["manifest/templates"]
  ignoredPath: []
  onPreInstall: 
    - path: manifest/templates/pre-install/print-num-job-01.yaml
      weight: "1"
  env: 
    - name: DEBUG
      value: ${DEBUG:-false}
    - name: DOMAIN
      value: ${DOMAIN:-coding.net}
  services:
    ${_INCLUDE_:-./base-services.yaml | nindent 4}
    - name: web
      serviceType: statefulset
      containers:
        - name: nginx
          dev:
            image: nocalhost-docker.pkg.coding.net/nocalhost/dev-images/ruby:3.0
            workDir: /home/nocalhost-web
