configProperties:
  version: v2
  envFile: env.dev

application:
  name: bookinfo
  manifestType: rawManifest
  resourcePath: ["manifest/templates"]
  ignoredPath: []
  onPreInstall:
    - path: manifest/templates/pre-install/print-num-job-01.yaml
      weight: "1"
    - path: manifest/templates/hook/pre-install.yaml
      weight: "1"
  onPostInstall:
    - path: manifest/templates/hook/post-install.yaml
      weight: "1"
  onPreUpgrade:
    - path: manifest/templates/hook/pre-upgrade.yaml
      weight: "1"
  onPostUpgrade:
    - path: manifest/templates/hook/post-upgrade.yaml
      weight: "1"
  onPreDelete:
    - path: manifest/templates/hook/pre-delete.yaml
      weight: "1"
  onPostDelete:
    - path: manifest/templates/hook/post-delete.yaml
      weight: "1"

  env:
    - name: DEBUG
      value: ${DEBUG:-false}
    - name: DOMAIN
      value: ${DOMAIN:-coding.net}
  services:
    ${_INCLUDE_:-./base-services.yaml | nindent 4}
    - name: web
      serviceType: statefulset
      containers:
        - name: nginx
          dev:
            image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/ruby:3.0
            workDir: /home/nocalhost-web
