- name: reviews
  serviceType: deployment
  dependLabelSelector:
    pods:
      - "productpage"
  containers:
    - dev:
        gitUrl: https://e.coding.net/nocalhost/nocalhost/bookinfo-reviews.git
        image: nocalhost-docker.pkg.coding.net/nocalhost/dev-images/java:latest
        shell: bash
        workDir: /home/nocalhost-dev
        command:
          build: [ "./gradlew", "build" ]
          run: [ "./gradlew", "bootRun" ]
          debug: [ "./gradlew", "bootRun", "--debug-jvm" ]
        debug:
          remoteDebugPort: 5005
        sync:
          type: send
          filePattern:
            - ./
          ignoreFilePattern:
            - ".git"
            - ".github"
            - ".gradle"
            - "build"
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "0.5"
            memory: 512Mi
      install:
        env:
          - name: ENV_INJECT_EXAM
            value: ANNOTATIONS