---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app: ratings
    service: ratings
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  {{- if .Values.nocalhost.annotations.path.ratings }}
  annotations:
    nocalhost.dev: |-
      {{ .Files.Get .Values.nocalhost.annotations.path.ratings | nindent 6 }}
  {{- end }}
  labels:
    app: ratings
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
      - name: ratings
        image: codingcorp-docker.pkg.coding.net/nocalhost/bookinfo/ratings
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        {{- with .Values.resources.ratings }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
