---
apiVersion: v1
kind: Service
metadata:
  name: details
  labels:
    app: details
    service: details
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: http
  selector:
    app: details
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
  labels:
    app: details
spec:
  replicas: 2
  selector:
    matchLabels:
      app: details
  template:
    metadata:
      labels:
        app: details
    spec:
      containers:
      - name: details
        image: codingcorp-docker.pkg.coding.net/nocalhost/bookinfo/details:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          {{- toYaml .Values.bookinfo.deploy.resources | nindent 10 }}
