 ---
apiVersion: v1
kind: Service
metadata:
  name: authors
  labels:
    app: authors
    service: authors
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: authors
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authors
  {{- if .Values.nocalhost.annotations.path.authors }}
  annotations:
    dev.nocalhost: |-
      {{ .Files.Get .Values.nocalhost.annotations.path.authors | nindent 6 }}
  {{- end }}
  labels:
    app: authors
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authors
  template:
    metadata:
      labels:
        app: authors
    spec:
      containers:
      - name: authors
        image: nocalhost-docker.pkg.coding.net/nocalhost/bookinfo/authors
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        {{- with .Values.resources.authors }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}

