---
apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app: reviews
    service: reviews
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: http
  selector:
    app: reviews
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  labels:
    app: reviews
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - name: reviews
        image: nocalhost-docker.pkg.coding.net/nocalhost/bookinfo/reviews:latest
        env:
        - name: server.port
          value: "{{ .Values.service.port }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          {{- toYaml .Values.bookinfo.deploy.resources | nindent 10 }}

        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.port }}
          failureThreshold: 1
          periodSeconds: 10
