---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app: ratings
    service: ratings
spec:
  ports:
  - port: {{ .Values.service.port }}
    name: http
  selector:
    app: ratings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  labels:
    app: ratings
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
      - name: ratings
        image: codingcorp-docker.pkg.coding.net/nocalhost/bookinfo/ratings:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          {{- toYaml .Values.bookinfo.deploy.resources | nindent 10 }}
